# --- ESTRUCTURA ---
IniciarPartido:IniciarPartido
InicioPartido:InicioPartido
FinPartido:FinPartido
FinJugada:FinJugada
Local:Local
Visitante:Visitante

# --- COMANDOS ---
Liga:Liga
Revancha:Revancha
Copa:Copa
Entrenamiento:Entrenamiento
Pretemporada:Pretemporada
Temporada:Temporada
Narrar:Narrar
ResultadoFinal:ResultadoFinal

# --- TIPOS DE DATOS ---
Dorsal:Dorsal
Decimal:Decimal
JugadaTexto:JugadaTexto

# --- OPERADORES Y ASIGNACIÓN ---
Ficha:Ficha
Gana:Gana
Pierde:Pierde
Empata:Empata
GolSuma:GolSuma
Contraataque:Contraataque