
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

import java_cup.runtime.Symbol;
<<<<<<< HEAD
import modelos.SimboloSemantico.TipoDato;
import modelos.ExprResult;
import modelos.Generador3Dir;
import modelos.AnalizadorSemantico;
=======
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
<<<<<<< HEAD
    "\000\055\000\002\002\004\000\002\002\007\000\002\002" +
    "\004\000\002\016\002\000\002\005\006\000\002\003\004" +
    "\000\002\003\002\000\002\004\007\000\002\004\006\000" +
    "\002\017\002\000\002\004\012\000\002\020\002\000\002" +
    "\004\010\000\002\021\002\000\002\004\012\000\002\022" +
    "\002\000\002\023\002\000\002\004\015\000\002\004\007" +
    "\000\002\004\005\000\002\015\003\000\002\015\003\000" +
    "\002\015\003\000\002\015\003\000\002\015\003\000\002" +
    "\014\003\000\002\014\003\000\002\014\005\000\002\014" +
    "\003\000\002\014\005\000\002\014\005\000\002\010\004" +
    "\000\002\010\002\000\002\011\005\000\002\011\005\000" +
    "\002\011\005\000\002\012\006\000\002\013\005\000\002" +
    "\013\005\000\002\024\002\000\002\006\011\000\002\006" +
    "\002\000\002\025\002\000\002\007\005\000\002\007\002" +
    "" });
=======
    "\000\045\000\002\002\004\000\002\002\007\000\002\002" +
    "\004\000\002\003\004\000\002\003\002\000\002\004\007" +
    "\000\002\004\006\000\002\004\011\000\002\004\007\000" +
    "\002\004\011\000\002\004\013\000\002\004\007\000\002" +
    "\004\005\000\002\010\003\000\002\010\003\000\002\010" +
    "\003\000\002\010\003\000\002\010\003\000\002\005\005" +
    "\000\002\006\005\000\002\006\005\000\002\006\005\000" +
    "\002\015\004\000\002\015\002\000\002\007\003\000\002" +
    "\007\003\000\002\007\003\000\002\007\005\000\002\007" +
    "\005\000\002\007\005\000\002\013\006\000\002\014\005" +
    "\000\002\014\005\000\002\011\010\000\002\011\002\000" +
    "\002\012\004\000\002\012\002" });
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
<<<<<<< HEAD
    "\000\152\000\016\012\011\023\006\024\013\025\005\026" +
    "\012\027\004\001\002\000\004\040\uffeb\001\002\000\004" +
    "\040\uffea\001\002\000\004\040\uffed\001\002\000\004\002" +
    "\154\001\002\000\004\040\150\001\002\000\004\013\014" +
    "\001\002\000\004\040\uffe9\001\002\000\004\040\uffec\001" +
    "\002\000\034\004\ufffe\007\ufffe\010\ufffe\011\ufffe\014\ufffe" +
    "\016\ufffe\017\ufffe\023\ufffe\024\ufffe\025\ufffe\026\ufffe\027" +
    "\ufffe\040\ufffe\001\002\000\004\002\uffff\001\002\000\034" +
    "\004\ufffb\007\ufffb\010\ufffb\011\ufffb\014\ufffb\016\ufffb\017" +
    "\ufffb\023\ufffb\024\ufffb\025\ufffb\026\ufffb\027\ufffb\040\ufffb" +
    "\001\002\000\034\004\030\007\024\010\026\011\020\014" +
    "\023\016\021\017\027\023\006\024\013\025\005\026\012" +
    "\027\004\040\031\001\002\000\004\021\125\001\002\000" +
    "\012\040\035\041\033\043\037\044\034\001\002\000\034" +
    "\004\ufffc\007\ufffc\010\ufffc\011\ufffc\014\ufffc\016\ufffc\017" +
    "\ufffc\023\ufffc\024\ufffc\025\ufffc\026\ufffc\027\ufffc\040\ufffc" +
    "\001\002\000\042\002\ufffd\004\ufffd\005\ufffd\006\ufffd\007" +
    "\ufffd\010\ufffd\011\ufffd\014\ufffd\016\ufffd\017\ufffd\023\ufffd" +
    "\024\ufffd\025\ufffd\026\ufffd\027\ufffd\040\ufffd\001\002\000" +
    "\004\021\116\001\002\000\004\040\112\001\002\000\004" +
    "\013\ufff4\001\002\000\004\021\077\001\002\000\004\021" +
    "\050\001\002\000\004\020\032\001\002\000\012\040\035" +
    "\041\033\043\037\044\034\001\002\000\006\041\uffe1\042" +
    "\uffe1\001\002\000\014\015\uffe7\022\uffe7\030\uffe7\031\uffe7" +
    "\032\uffe7\001\002\000\020\015\uffe5\022\uffe5\030\uffe5\031" +
    "\uffe5\032\uffe5\036\042\037\041\001\002\000\004\015\040" +
    "\001\002\000\014\015\uffe8\022\uffe8\030\uffe8\031\uffe8\032" +
    "\uffe8\001\002\000\034\004\ufff9\007\ufff9\010\ufff9\011\ufff9" +
    "\014\ufff9\016\ufff9\017\ufff9\023\ufff9\024\ufff9\025\ufff9\026" +
    "\ufff9\027\ufff9\040\ufff9\001\002\000\012\040\035\041\033" +
    "\043\037\044\034\001\002\000\012\040\035\041\033\043" +
    "\037\044\034\001\002\000\014\015\uffe4\022\uffe4\030\uffe4" +
    "\031\uffe4\032\uffe4\001\002\000\014\015\uffe3\022\uffe3\030" +
    "\uffe3\031\uffe3\032\uffe3\001\002\000\006\041\046\042\047" +
    "\001\002\000\014\015\uffe6\022\uffe6\030\uffe6\031\uffe6\032" +
    "\uffe6\001\002\000\006\041\uffe2\042\uffe2\001\002\000\012" +
    "\040\035\041\033\043\037\044\034\001\002\000\004\022" +
    "\061\001\002\000\010\030\054\031\053\032\055\001\002" +
    "\000\012\040\035\041\033\043\037\044\034\001\002\000" +
    "\012\040\035\041\033\043\037\044\034\001\002\000\012" +
    "\040\035\041\033\043\037\044\034\001\002\000\006\015" +
    "\uffde\022\uffde\001\002\000\006\015\uffe0\022\uffe0\001\002" +
    "\000\006\015\uffdf\022\uffdf\001\002\000\004\013\ufff8\001" +
    "\002\000\004\013\014\001\002\000\040\004\uffd8\005\uffd8" +
    "\006\uffd8\007\uffd8\010\uffd8\011\uffd8\014\uffd8\016\uffd8\017" +
    "\uffd8\023\uffd8\024\uffd8\025\uffd8\026\uffd8\027\uffd8\040\uffd8" +
    "\001\002\000\040\004\uffd5\005\065\006\067\007\uffd5\010" +
    "\uffd5\011\uffd5\014\uffd5\016\uffd5\017\uffd5\023\uffd5\024\uffd5" +
    "\025\uffd5\026\uffd5\027\uffd5\040\uffd5\001\002\000\004\021" +
    "\072\001\002\000\034\004\ufff7\007\ufff7\010\ufff7\011\ufff7" +
    "\014\ufff7\016\ufff7\017\ufff7\023\ufff7\024\ufff7\025\ufff7\026" +
    "\ufff7\027\ufff7\040\ufff7\001\002\000\004\013\uffd7\001\002" +
    "\000\004\013\014\001\002\000\034\004\uffd6\007\uffd6\010" +
    "\uffd6\011\uffd6\014\uffd6\016\uffd6\017\uffd6\023\uffd6\024\uffd6" +
    "\025\uffd6\026\uffd6\027\uffd6\040\uffd6\001\002\000\012\040" +
    "\035\041\033\043\037\044\034\001\002\000\004\022\074" +
    "\001\002\000\004\013\uffda\001\002\000\004\013\014\001" +
    "\002\000\040\004\uffd9\005\uffd9\006\uffd9\007\uffd9\010\uffd9" +
    "\011\uffd9\014\uffd9\016\uffd9\017\uffd9\023\uffd9\024\uffd9\025" +
    "\uffd9\026\uffd9\027\uffd9\040\uffd9\001\002\000\012\040\035" +
    "\041\033\043\037\044\034\001\002\000\004\022\101\001" +
    "\002\000\004\015\102\001\002\000\034\004\uffef\007\uffef" +
    "\010\uffef\011\uffef\014\uffef\016\uffef\017\uffef\023\uffef\024" +
    "\uffef\025\uffef\026\uffef\027\uffef\040\uffef\001\002\000\004" +
    "\013\014\001\002\000\004\007\105\001\002\000\004\021" +
    "\106\001\002\000\012\040\035\041\033\043\037\044\034" +
    "\001\002\000\004\022\110\001\002\000\004\015\111\001" +
    "\002\000\034\004\ufff3\007\ufff3\010\ufff3\011\ufff3\014\ufff3" +
    "\016\ufff3\017\ufff3\023\ufff3\024\ufff3\025\ufff3\026\ufff3\027" +
    "\ufff3\040\ufff3\001\002\000\004\020\113\001\002\000\012" +
    "\040\035\041\033\043\037\044\034\001\002\000\004\015" +
    "\115\001\002\000\034\004\ufffa\007\ufffa\010\ufffa\011\ufffa" +
    "\014\ufffa\016\ufffa\017\ufffa\023\ufffa\024\ufffa\025\ufffa\026" +
    "\ufffa\027\ufffa\040\ufffa\001\002\000\012\040\035\041\033" +
    "\043\037\044\034\001\002\000\004\022\120\001\002\000" +
    "\004\013\ufff6\001\002\000\004\013\014\001\002\000\034" +
    "\004\ufff5\007\ufff5\010\ufff5\011\ufff5\014\ufff5\016\ufff5\017" +
    "\ufff5\023\ufff5\024\ufff5\025\ufff5\026\ufff5\027\ufff5\040\ufff5" +
    "\001\002\000\004\015\124\001\002\000\034\004\uffee\007" +
    "\uffee\010\uffee\011\uffee\014\uffee\016\uffee\017\uffee\023\uffee" +
    "\024\uffee\025\uffee\026\uffee\027\uffee\040\uffee\001\002\000" +
    "\014\023\ufff2\024\ufff2\025\ufff2\026\ufff2\027\ufff2\001\002" +
    "\000\014\023\006\024\013\025\005\026\012\027\004\001" +
    "\002\000\004\015\134\001\002\000\004\040\131\001\002" +
    "\000\004\020\132\001\002\000\012\040\035\041\033\043" +
    "\037\044\034\001\002\000\004\015\uffdd\001\002\000\012" +
    "\040\035\041\033\043\037\044\034\001\002\000\004\015" +
    "\136\001\002\000\004\040\140\001\002\000\004\022\145" +
    "\001\002\000\006\036\142\037\141\001\002\000\012\040" +
    "\035\041\033\043\037\044\034\001\002\000\012\040\035" +
    "\041\033\043\037\044\034\001\002\000\004\022\uffdc\001" +
    "\002\000\004\022\uffdb\001\002\000\004\013\ufff1\001\002" +
    "\000\004\013\014\001\002\000\034\004\ufff0\007\ufff0\010" +
    "\ufff0\011\ufff0\014\ufff0\016\ufff0\017\ufff0\023\ufff0\024\ufff0" +
    "\025\ufff0\026\ufff0\027\ufff0\040\ufff0\001\002\000\004\021" +
    "\151\001\002\000\004\022\152\001\002\000\004\013\014" +
    "\001\002\000\004\002\000\001\002\000\004\002\001\001" +
    "\002" });
=======
    "\000\142\000\016\012\011\023\006\024\013\025\005\026" +
    "\012\027\004\001\002\000\004\040\ufff0\001\002\000\004" +
    "\040\ufff2\001\002\000\004\040\ufff4\001\002\000\004\002" +
    "\144\001\002\000\004\040\140\001\002\000\004\013\014" +
    "\001\002\000\004\040\ufff1\001\002\000\004\040\ufff3\001" +
    "\002\000\034\004\ufffd\007\ufffd\010\ufffd\011\ufffd\014\ufffd" +
    "\016\ufffd\017\ufffd\023\ufffd\024\ufffd\025\ufffd\026\ufffd\027" +
    "\ufffd\040\ufffd\001\002\000\004\002\uffff\001\002\000\034" +
    "\004\030\007\023\010\025\011\017\014\022\016\020\017" +
    "\026\023\006\024\013\025\005\026\012\027\004\040\027" +
    "\001\002\000\004\021\117\001\002\000\012\040\034\041" +
    "\032\043\036\044\033\001\002\000\034\004\ufffe\007\ufffe" +
    "\010\ufffe\011\ufffe\014\ufffe\016\ufffe\017\ufffe\023\ufffe\024" +
    "\ufffe\025\ufffe\026\ufffe\027\ufffe\040\ufffe\001\002\000\042" +
    "\002\uffef\004\uffef\005\uffef\006\uffef\007\uffef\010\uffef\011" +
    "\uffef\014\uffef\016\uffef\017\uffef\023\uffef\024\uffef\025\uffef" +
    "\026\uffef\027\uffef\040\uffef\001\002\000\004\021\111\001" +
    "\002\000\004\040\105\001\002\000\004\013\014\001\002" +
    "\000\004\021\073\001\002\000\004\020\070\001\002\000" +
    "\004\021\031\001\002\000\012\040\034\041\032\043\036" +
    "\044\033\001\002\000\006\041\uffea\042\uffea\001\002\000" +
    "\014\015\uffe8\022\uffe8\030\uffe8\031\uffe8\032\uffe8\001\002" +
    "\000\020\015\uffe7\022\uffe7\030\uffe7\031\uffe7\032\uffe7\036" +
    "\062\037\061\001\002\000\004\022\046\001\002\000\014" +
    "\015\uffe9\022\uffe9\030\uffe9\031\uffe9\032\uffe9\001\002\000" +
    "\010\030\041\031\040\032\042\001\002\000\012\040\034" +
    "\041\032\043\036\044\033\001\002\000\012\040\034\041" +
    "\032\043\036\044\033\001\002\000\012\040\034\041\032" +
    "\043\036\044\033\001\002\000\006\015\uffec\022\uffec\001" +
    "\002\000\006\015\uffee\022\uffee\001\002\000\006\015\uffed" +
    "\022\uffed\001\002\000\004\013\014\001\002\000\040\004" +
    "\uffdf\005\uffdf\006\uffdf\007\uffdf\010\uffdf\011\uffdf\014\uffdf" +
    "\016\uffdf\017\uffdf\023\uffdf\024\uffdf\025\uffdf\026\uffdf\027" +
    "\uffdf\040\uffdf\001\002\000\040\004\uffdd\005\051\006\053" +
    "\007\uffdd\010\uffdd\011\uffdd\014\uffdd\016\uffdd\017\uffdd\023" +
    "\uffdd\024\uffdd\025\uffdd\026\uffdd\027\uffdd\040\uffdd\001\002" +
    "\000\004\021\055\001\002\000\034\004\ufffa\007\ufffa\010" +
    "\ufffa\011\ufffa\014\ufffa\016\ufffa\017\ufffa\023\ufffa\024\ufffa" +
    "\025\ufffa\026\ufffa\027\ufffa\040\ufffa\001\002\000\004\013" +
    "\014\001\002\000\034\004\uffde\007\uffde\010\uffde\011\uffde" +
    "\014\uffde\016\uffde\017\uffde\023\uffde\024\uffde\025\uffde\026" +
    "\uffde\027\uffde\040\uffde\001\002\000\012\040\034\041\032" +
    "\043\036\044\033\001\002\000\004\022\057\001\002\000" +
    "\004\013\014\001\002\000\040\004\uffe0\005\uffe0\006\uffe0" +
    "\007\uffe0\010\uffe0\011\uffe0\014\uffe0\016\uffe0\017\uffe0\023" +
    "\uffe0\024\uffe0\025\uffe0\026\uffe0\027\uffe0\040\uffe0\001\002" +
    "\000\012\040\034\041\032\043\036\044\033\001\002\000" +
    "\012\040\034\041\032\043\036\044\033\001\002\000\014" +
    "\015\uffe5\022\uffe5\030\uffe5\031\uffe5\032\uffe5\001\002\000" +
    "\014\015\uffe4\022\uffe4\030\uffe4\031\uffe4\032\uffe4\001\002" +
    "\000\006\041\066\042\067\001\002\000\014\015\uffe6\022" +
    "\uffe6\030\uffe6\031\uffe6\032\uffe6\001\002\000\006\041\uffeb" +
    "\042\uffeb\001\002\000\012\040\034\041\032\043\036\044" +
    "\033\001\002\000\004\015\072\001\002\000\034\004\ufffb" +
    "\007\ufffb\010\ufffb\011\ufffb\014\ufffb\016\ufffb\017\ufffb\023" +
    "\ufffb\024\ufffb\025\ufffb\026\ufffb\027\ufffb\040\ufffb\001\002" +
    "\000\012\040\034\041\032\043\036\044\033\001\002\000" +
    "\004\022\075\001\002\000\004\015\076\001\002\000\034" +
    "\004\ufff6\007\ufff6\010\ufff6\011\ufff6\014\ufff6\016\ufff6\017" +
    "\ufff6\023\ufff6\024\ufff6\025\ufff6\026\ufff6\027\ufff6\040\ufff6" +
    "\001\002\000\004\007\100\001\002\000\004\021\101\001" +
    "\002\000\012\040\034\041\032\043\036\044\033\001\002" +
    "\000\004\022\103\001\002\000\004\015\104\001\002\000" +
    "\034\004\ufff8\007\ufff8\010\ufff8\011\ufff8\014\ufff8\016\ufff8" +
    "\017\ufff8\023\ufff8\024\ufff8\025\ufff8\026\ufff8\027\ufff8\040" +
    "\ufff8\001\002\000\004\020\106\001\002\000\012\040\034" +
    "\041\032\043\036\044\033\001\002\000\004\015\110\001" +
    "\002\000\034\004\ufffc\007\ufffc\010\ufffc\011\ufffc\014\ufffc" +
    "\016\ufffc\017\ufffc\023\ufffc\024\ufffc\025\ufffc\026\ufffc\027" +
    "\ufffc\040\ufffc\001\002\000\012\040\034\041\032\043\036" +
    "\044\033\001\002\000\004\022\113\001\002\000\004\013" +
    "\014\001\002\000\034\004\ufff9\007\ufff9\010\ufff9\011\ufff9" +
    "\014\ufff9\016\ufff9\017\ufff9\023\ufff9\024\ufff9\025\ufff9\026" +
    "\ufff9\027\ufff9\040\ufff9\001\002\000\004\015\116\001\002" +
    "\000\034\004\ufff5\007\ufff5\010\ufff5\011\ufff5\014\ufff5\016" +
    "\ufff5\017\ufff5\023\ufff5\024\ufff5\025\ufff5\026\ufff5\027\ufff5" +
    "\040\ufff5\001\002\000\014\023\006\024\013\025\005\026" +
    "\012\027\004\001\002\000\004\015\125\001\002\000\004" +
    "\040\122\001\002\000\004\020\123\001\002\000\012\040" +
    "\034\041\032\043\036\044\033\001\002\000\004\015\uffe3" +
    "\001\002\000\012\040\034\041\032\043\036\044\033\001" +
    "\002\000\004\015\127\001\002\000\004\040\131\001\002" +
    "\000\004\022\136\001\002\000\006\036\133\037\132\001" +
    "\002\000\012\040\034\041\032\043\036\044\033\001\002" +
    "\000\012\040\034\041\032\043\036\044\033\001\002\000" +
    "\004\022\uffe2\001\002\000\004\022\uffe1\001\002\000\004" +
    "\013\014\001\002\000\034\004\ufff7\007\ufff7\010\ufff7\011" +
    "\ufff7\014\ufff7\016\ufff7\017\ufff7\023\ufff7\024\ufff7\025\ufff7" +
    "\026\ufff7\027\ufff7\040\ufff7\001\002\000\004\021\141\001" +
    "\002\000\004\022\142\001\002\000\004\013\014\001\002" +
    "\000\004\002\000\001\002\000\004\002\001\001\002" });
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
<<<<<<< HEAD
    "\000\152\000\006\002\006\015\007\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\014\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\016\015\001\001\000\002" +
    "\001\001\000\004\003\016\001\001\000\006\004\021\015" +
    "\024\001\001\000\002\001\001\000\004\014\122\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\021\102\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\014\035\001" +
    "\001\000\004\010\044\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\014\043\001\001\000\004\014\042\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\011\050\014\051" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\057\001\001\000\004\014\056\001\001\000\004\014\055" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\017\061\001\001\000\004\005\062\001\001" +
    "\000\004\006\063\001\001\000\004\007\065\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\025\067\001\001" +
    "\000\004\005\070\001\001\000\002\001\001\000\006\011" +
    "\072\014\051\001\001\000\002\001\001\000\004\024\074" +
    "\001\001\000\004\005\075\001\001\000\002\001\001\000" +
    "\004\014\077\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\103\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\011\106\014\051\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\113\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\011\116\014\051\001\001\000" +
    "\002\001\001\000\004\020\120\001\001\000\004\005\121" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\022\125\001\001\000\006\012\126\015\127" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\014\132\001\001\000\002\001\001\000\006" +
    "\011\134\014\051\001\001\000\002\001\001\000\004\013" +
    "\136\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\014\143\001\001\000\004\014\142\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\023\145\001\001\000\004" +
    "\005\146\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\152\001\001\000\002\001\001" +
    "\000\002\001\001" });
=======
    "\000\142\000\006\002\006\010\007\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\014\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\003\015\001\001\000\002" +
    "\001\001\000\006\004\020\010\023\001\001\000\002\001" +
    "\001\000\004\007\114\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\076\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\006\034\007\036\001\001\000\004\015" +
    "\064\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\007" +
    "\044\001\001\000\004\007\043\001\001\000\004\007\042" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\005\046\001\001\000\004\011\047\001\001" +
    "\000\004\012\051\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\005\053\001\001\000\002\001\001\000\006" +
    "\006\055\007\036\001\001\000\002\001\001\000\004\005" +
    "\057\001\001\000\002\001\001\000\004\007\063\001\001" +
    "\000\004\007\062\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\007\070\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\073\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\006\101\007\036\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\106\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\006\111\007\036\001\001\000\002\001\001\000" +
    "\004\005\113\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\010\120\013\117\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\007\123\001\001\000\002\001\001\000\006\006\125\007" +
    "\036\001\001\000\002\001\001\000\004\014\127\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\007\134\001" +
    "\001\000\004\007\133\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\005\136\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\142\001\001" +
    "\000\002\001\001\000\002\001\001" });
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol s) {
<<<<<<< HEAD
        String lexema = s.value != null ? s.value.toString() : "Desconocido";
        modelos.TablaGlobal.errores.add(
            new modelos.ErrorCompilador("Sintáctico",
                "No se esperaba el token: " + lexema, s.left));
=======
        // Esto envía el error sintáctico directo a tu tabla HTML
        String lexema = s.value != null ? s.value.toString() : "Desconocido";
        modelos.TablaGlobal.errores.add(new modelos.ErrorCompilador("Sintáctico", "No se esperaba el token: " + lexema, s.left));
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= tipo_dato IDENTIFICADOR Local Visitante bloque 
            {
              Object RESULT =null;
<<<<<<< HEAD
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		TipoDato t = (TipoDato)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		
            AnalizadorSemantico.declararVariable(t, id.toString(), idleft, true);
        
=======

>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= IniciarPartido bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 3: // NT$0 ::= 
            {
              Object RESULT =null;
		int ipleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int ipright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object ip = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
 AnalizadorSemantico.abrirScope(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$0",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // bloque ::= InicioPartido NT$0 lista_instrucciones FinPartido 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int ipleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int ipright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object ip = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		 AnalizadorSemantico.cerrarScope(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_instrucciones ::= lista_instrucciones instruccion 
=======
          case 3: // lista_instrucciones ::= lista_instrucciones instruccion 
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 6: // lista_instrucciones ::= 
=======
          case 4: // lista_instrucciones ::= 
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 7: // instruccion ::= tipo_dato IDENTIFICADOR Ficha expresion FinJugada 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		TipoDato t = (TipoDato)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		modelos.ExprResult e = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
            String tipoCpp = Generador3Dir.tipoCpp(t);
            TipoDato tipoVar = AnalizadorSemantico.declararVariable(
                t, id.toString(), idleft, true);
            AnalizadorSemantico.verificarCompatibilidad(tipoVar, e.tipo, idleft);
            Generador3Dir.emitirAsignacion(id.toString(), e.valor, idleft, tipoCpp);
        
=======
          case 5: // instruccion ::= tipo_dato IDENTIFICADOR Ficha expresion FinJugada 
            {
              Object RESULT =null;

>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 8: // instruccion ::= IDENTIFICADOR Ficha expresion FinJugada 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		modelos.ExprResult e = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
            TipoDato tipoVar = AnalizadorSemantico.verificarAsignacion(
                id.toString(), idleft);
            AnalizadorSemantico.verificarCompatibilidad(tipoVar, e.tipo, idleft);
            Generador3Dir.emitirAsignacion(id.toString(), e.valor, idleft);
        
=======
          case 6: // instruccion ::= IDENTIFICADOR Ficha expresion FinJugada 
            {
              Object RESULT =null;

>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 9: // NT$1 ::= 
            {
              Object RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String cond = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;

            AnalizadorSemantico.entrarCondicional();
            Generador3Dir.emitirIfInicio(cond);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$1",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 7: // instruccion ::= Liga Local condicion Visitante bloque lista_revancha opcion_copa 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 10: // instruccion ::= Liga Local condicion Visitante NT$1 bloque lista_revancha opcion_copa 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String cond = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		
            AnalizadorSemantico.salirCondicional();
            Generador3Dir.emitirIfFin();
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$2 ::= 
            {
              Object RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String cond = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;

            AnalizadorSemantico.entrarCiclo();
            Generador3Dir.emitirWhileInicio(cond);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$2",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // instruccion ::= Entrenamiento Local condicion Visitante NT$2 bloque 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String cond = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		
            AnalizadorSemantico.salirCiclo();
            Generador3Dir.emitirWhileFin();
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // NT$3 ::= 
            {
              Object RESULT =null;

            AnalizadorSemantico.entrarCiclo();
            Generador3Dir.emitirDoWhileInicio();
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$3",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // instruccion ::= Pretemporada NT$3 bloque Entrenamiento Local condicion Visitante FinJugada 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String cond = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
            AnalizadorSemantico.salirCiclo();
            Generador3Dir.emitirDoWhileFin(cond);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NT$4 ::= 
            {
              Object RESULT =null;
  AnalizadorSemantico.entrarCiclo(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$4",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // NT$5 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int inileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int iniright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String ini = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String cond = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int updleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int updright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String upd = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
  Generador3Dir.emitirForInicio(ini, cond, upd); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$5",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // instruccion ::= Temporada Local NT$4 inicializacion FinJugada condicion FinJugada actualizacion Visitante NT$5 bloque 
            {
              Object RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int inileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int iniright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		String ini = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String cond = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int updleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int updright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String upd = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		
            AnalizadorSemantico.salirCiclo();
            Generador3Dir.emitirForFin();
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // instruccion ::= Narrar Local expresion Visitante FinJugada 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		modelos.ExprResult e = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		  Generador3Dir.emitirNarrar(e.valor, eleft); 
=======
          case 8: // instruccion ::= Entrenamiento Local condicion Visitante bloque 
            {
              Object RESULT =null;

>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 19: // instruccion ::= ResultadoFinal expresion FinJugada 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		modelos.ExprResult e = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
            AnalizadorSemantico.verificarResultadoFinal(e.tipo, eleft);
            Generador3Dir.emitirComentario("return " + e.valor);
        
=======
          case 9: // instruccion ::= Pretemporada bloque Entrenamiento Local condicion Visitante FinJugada 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion ::= Temporada Local inicializacion FinJugada condicion FinJugada actualizacion Visitante bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // instruccion ::= Narrar Local expresion Visitante FinJugada 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // instruccion ::= ResultadoFinal expresion FinJugada 
            {
              Object RESULT =null;

>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 20: // tipo_dato ::= Dorsal 
            {
              TipoDato RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = TipoDato.DORSAL;      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 13: // tipo_dato ::= Dorsal 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 21: // tipo_dato ::= Decimal 
            {
              TipoDato RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = TipoDato.DECIMAL;     
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 14: // tipo_dato ::= Decimal 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 22: // tipo_dato ::= JugadaTexto 
            {
              TipoDato RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = TipoDato.JUGADATEXTO; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 15: // tipo_dato ::= Marcador 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 23: // tipo_dato ::= Marcador 
            {
              TipoDato RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = TipoDato.DORSAL;       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 16: // tipo_dato ::= Letra 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 24: // tipo_dato ::= Letra 
            {
              TipoDato RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = TipoDato.JUGADATEXTO; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 17: // tipo_dato ::= JugadaTexto 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 25: // expresion ::= ENTERO 
            {
              modelos.ExprResult RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer v = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new modelos.ExprResult(TipoDato.DORSAL, v.toString()); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 18: // bloque ::= InicioPartido lista_instrucciones FinPartido 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 26: // expresion ::= DECIMAL_LITERAL 
            {
              modelos.ExprResult RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Double v = (Double)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new modelos.ExprResult(TipoDato.DECIMAL, v.toString()); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 19: // condicion ::= expresion Gana expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // condicion ::= expresion Pierde expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // condicion ::= expresion Empata expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // contenido_relato ::= contenido_relato TEXTO_CONTENIDO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("contenido_relato",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // contenido_relato ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("contenido_relato",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expresion ::= ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expresion ::= DECIMAL_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expresion ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expresion ::= RELATO contenido_relato RELATO 
            {
<<<<<<< HEAD
              modelos.ExprResult RESULT =null;
		 RESULT = new modelos.ExprResult(TipoDato.JUGADATEXTO, "\"\""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 28: // expresion ::= IDENTIFICADOR 
            {
              modelos.ExprResult RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            TipoDato t = AnalizadorSemantico.verificarUso(id.toString(), idleft);
            RESULT = new modelos.ExprResult(t, id.toString());
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expresion ::= IDENTIFICADOR GolSuma expresion 
            {
              modelos.ExprResult RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		modelos.ExprResult e = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            TipoDato tipoId  = AnalizadorSemantico.verificarUso(id.toString(), idleft);
            TipoDato tipoRes = AnalizadorSemantico.verificarOperacionAritmetica(
                tipoId, e.tipo, "GolSuma", idleft);
            String tipoCpp = Generador3Dir.tipoCpp(tipoRes);
            String temp = Generador3Dir.emitirOperacion(
                id.toString(), "+", e.valor, idleft, tipoCpp);
            RESULT = new modelos.ExprResult(tipoRes, temp);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expresion ::= IDENTIFICADOR Contraataque expresion 
            {
              modelos.ExprResult RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		modelos.ExprResult e = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            TipoDato tipoId  = AnalizadorSemantico.verificarUso(id.toString(), idleft);
            TipoDato tipoRes = AnalizadorSemantico.verificarOperacionAritmetica(
                tipoId, e.tipo, "Contraataque", idleft);
            String tipoCpp = Generador3Dir.tipoCpp(tipoRes);
            String temp = Generador3Dir.emitirOperacion(
                id.toString(), "-", e.valor, idleft, tipoCpp);
            RESULT = new modelos.ExprResult(tipoRes, temp);
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // contenido_relato ::= contenido_relato TEXTO_CONTENIDO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("contenido_relato",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 28: // expresion ::= IDENTIFICADOR GolSuma expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 32: // contenido_relato ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("contenido_relato",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 29: // expresion ::= IDENTIFICADOR Contraataque expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 33: // condicion ::= expresion Gana expresion 
            {
              String RESULT =null;
		int izqleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int izqright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		modelos.ExprResult izq = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int derleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int derright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		modelos.ExprResult der = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = izq.valor + " > "  + der.valor; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condicion ::= expresion Pierde expresion 
            {
              String RESULT =null;
		int izqleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int izqright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		modelos.ExprResult izq = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int derleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int derright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		modelos.ExprResult der = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = izq.valor + " < "  + der.valor; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condicion ::= expresion Empata expresion 
            {
              String RESULT =null;
		int izqleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int izqright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		modelos.ExprResult izq = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int derleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int derright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		modelos.ExprResult der = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = izq.valor + " == " + der.valor; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // inicializacion ::= tipo_dato IDENTIFICADOR Ficha expresion 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		TipoDato t = (TipoDato)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		modelos.ExprResult e = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            String tipoCpp = Generador3Dir.tipoCpp(t);
            TipoDato tipoVar = AnalizadorSemantico.declararVariable(
                t, id.toString(), idleft, true);
            AnalizadorSemantico.verificarCompatibilidad(tipoVar, e.tipo, idleft);
            Generador3Dir.registrarVariable(id.toString(), tipoCpp);
            RESULT = tipoCpp + " " + id.toString() + " = " + e.valor;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("inicializacion",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // actualizacion ::= IDENTIFICADOR GolSuma expresion 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		modelos.ExprResult e = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            AnalizadorSemantico.verificarAsignacion(id.toString(), idleft);
            RESULT = id.toString() + " = " + id.toString() + " + " + e.valor;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actualizacion",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // actualizacion ::= IDENTIFICADOR Contraataque expresion 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		modelos.ExprResult e = (modelos.ExprResult)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
            AnalizadorSemantico.verificarAsignacion(id.toString(), idleft);
            RESULT = id.toString() + " = " + id.toString() + " - " + e.valor;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actualizacion",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // NT$6 ::= 
            {
              Object RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String cond = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
 Generador3Dir.emitirElseIfInicio(cond); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$6",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // lista_revancha ::= lista_revancha Revancha Local condicion Visitante NT$6 bloque 
            {
              Object RESULT =null;
              // propagate RESULT from NT$6
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String cond = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_revancha",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // lista_revancha ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_revancha",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 30: // inicializacion ::= tipo_dato IDENTIFICADOR Ficha expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("inicializacion",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 42: // NT$7 ::= 
            {
              Object RESULT =null;
 Generador3Dir.emitirElseInicio(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$7",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 31: // actualizacion ::= IDENTIFICADOR GolSuma expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actualizacion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 43: // opcion_copa ::= Copa NT$7 bloque 
            {
              Object RESULT =null;
              // propagate RESULT from NT$7
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 Generador3Dir.emitirElseFin(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opcion_copa",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 32: // actualizacion ::= IDENTIFICADOR Contraataque expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actualizacion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< HEAD
          case 44: // opcion_copa ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opcion_copa",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 33: // lista_revancha ::= lista_revancha Revancha Local condicion Visitante bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_revancha",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // lista_revancha ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_revancha",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // opcion_copa ::= Copa bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opcion_copa",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // opcion_copa ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opcion_copa",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> 7811fd0017ca6c222942e7725fc8eb3d63c5a172
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
