
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Pretemporada = 6;
  public static final int FinJugada = 11;
  public static final int FinPartido = 10;
  public static final int Temporada = 7;
  public static final int GanaOEmpata = 26;
  public static final int DECIMAL_LITERAL = 34;
  public static final int Revancha = 3;
  public static final int GolSuma = 28;
  public static final int TEXTO_CONTENIDO = 32;
  public static final int Marcador = 19;
  public static final int Entrenamiento = 5;
  public static final int Liga = 2;
  public static final int Pierde = 23;
  public static final int Copa = 4;
  public static final int Contraataque = 29;
  public static final int Dorsal = 17;
  public static final int InicioPartido = 9;
  public static final int NoEmpata = 25;
  public static final int EOF = 0;
  public static final int PierdeOEmpata = 27;
  public static final int Gana = 22;
  public static final int JugadaTexto = 21;
  public static final int RELATO = 31;
  public static final int ResultadoFinal = 12;
  public static final int Decimal = 18;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 30;
  public static final int Empata = 24;
  public static final int ENTERO = 33;
  public static final int Letra = 20;
  public static final int Narrar = 13;
  public static final int Local = 15;
  public static final int IniciarPartido = 8;
  public static final int Ficha = 14;
  public static final int Visitante = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Liga",
  "Revancha",
  "Copa",
  "Entrenamiento",
  "Pretemporada",
  "Temporada",
  "IniciarPartido",
  "InicioPartido",
  "FinPartido",
  "FinJugada",
  "ResultadoFinal",
  "Narrar",
  "Ficha",
  "Local",
  "Visitante",
  "Dorsal",
  "Decimal",
  "Marcador",
  "Letra",
  "JugadaTexto",
  "Gana",
  "Pierde",
  "Empata",
  "NoEmpata",
  "GanaOEmpata",
  "PierdeOEmpata",
  "GolSuma",
  "Contraataque",
  "IDENTIFICADOR",
  "RELATO",
  "TEXTO_CONTENIDO",
  "ENTERO",
  "DECIMAL_LITERAL"
  };
}

